mssql:
  server: KRR-SQL-PACLX02
  user_id: "EUROPE\\%mssql_user%"
  password: "%mssql_password%"
  database: KRR-PA-RAW-Energy

connection:
  host: 10.21.2.139
  type: tcp

commands:
  - command: EMC !125m7827
    port: 52321
    id_measuring: 1688129916
    name: ASUWATER_WaterPipe_IngulSouth_Pipe1Pump_Fwater

  - command: EMC !125m7825
    port: 52325
    id_measuring: 1688129915
    name: ASUWATER_WaterPipe_IngulSouth_Pipe3Pump_Fwater

query_insert: INSERT INTO [dbo].[raw_source_132_analog] ([NAME], [id_measuring], [VALUE], [TIMESTAMP], [QUALITY], [BATCHID]) VALUES (?, ?, ?, ?, ?, ?)

timer: 5m
timeout: 2m
max_read_retries: 3
log_level: release